### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by grisevg** [theRemix/language-haxe#3]
Atom has recommended to create github issue to update usage of deprecated API:

Store package settings files in the `settings/` directory instead of `scoped-properties/`

```
Package.loadSettings (C:\Users\Eugene\AppData\Local\atom\app-0.191.0\resources\app\src\package.js:547:9)
<unknown> (C:\Users\Eugene\AppData\Local\atom\app-0.191.0\resources\app\src\package.js:168:43)
```

**Comment by theRemix** [comment]
fixed in 99e0acfd39c24d54e14ce2b08487ce78682f2b46
